Repository jhu-sheridan-libraries/jhuda-deposit-ui, pull requests merged in 2019-12, with the labels that each got.

#41 Required actions shown on dashboard
  app/components/app-header/template.hbs
  app/components/submission-title-cell/component.js
  app/components/submission-title-cell/template.hbs
  app/dashboard/route.js
  app/styles/app.css
  mirage/factories/submission-action.js
  mirage/factories/submission.js
  tests/integration/components/submission-title-cell-test.js
Labels: Dashboard, Deposit UI

#37 Add some stuff to the README
  README.md
Labels: Deposit UI, documentation

#44 Add Metadata Step
  app/components/metadata-form/author-form/component.js
  app/components/metadata-form/author-form/styles.css
  app/components/metadata-form/author-form/template.hbs
  app/components/metadata-form/component.js
  app/components/metadata-form/contact-form/component.js
  app/components/metadata-form/contact-form/styles.css
  app/components/metadata-form/contact-form/template.hbs
  app/components/metadata-form/detail-form/component.js
  app/components/metadata-form/detail-form/styles.css
  app/components/metadata-form/detail-form/template.hbs
  app/components/metadata-form/grant-form/component.js
  app/components/metadata-form/grant-form/styles.css
  app/components/metadata-form/grant-form/template.hbs
  app/components/metadata-form/publication-form/component.js
  app/components/metadata-form/publication-form/styles.css
  app/components/metadata-form/publication-form/template.hbs
  app/components/metadata-form/styles.css
  app/components/metadata-form/template.hbs
  app/components/workflow-footer/component.js
  app/components/workflow-footer/template.hbs
  app/initializers/custom-inflector-rules.js
  app/models/author.js
  app/models/contact.js
  app/models/grant.js
  app/models/metadata.js
  app/models/publication.js
  app/models/submission.js
  app/submission/workflow/agreements/controller.js
  app/submission/workflow/agreements/template.hbs
  app/submission/workflow/controller.js
  app/submission/workflow/files/controller.js
  app/submission/workflow/files/template.hbs
  app/submission/workflow/metadata/controller.js
  app/submission/workflow/metadata/route.js
  app/submission/workflow/metadata/template.hbs
  app/submission/workflow/template.hbs
  app/validations/author.js
  app/validations/contact.js
  app/validations/grant.js
  app/validations/metadata.js
  app/validations/publication.js
  ember-cli-build.js
  mirage/config.js
  mirage/factories/submission.js
  mirage/models/author.js
  mirage/models/contact.js
  mirage/models/grant.js
  mirage/models/metadata.js
  mirage/models/publication.js
  package.json
  tests/integration/components/metadata-form-test.js
  tests/integration/components/workflow-footer/component-test.js
  tests/unit/initializers/custom-inflector-rules-test.js
  tests/unit/models/author-test.js
  tests/unit/models/contact-test.js
  tests/unit/models/grant-test.js
  tests/unit/models/metadata-test.js
  tests/unit/models/publication-test.js
  tests/unit/submission/workflow/metadata/controller-test.js
  yarn.lock
Labels: Deposit UI

#43 Integrate fedora adapter
  .docker/.env
  .docker/docker-compose.yml
  .docker/ember-dev/Dockerfile
  .docker/secrets/idp/idp-backchannel.p12
  .docker/secrets/idp/idp-browser.p12
  .docker/secrets/idp/idp-encryption.key
  .docker/secrets/idp/idp-signing.key
  .docker/secrets/idp/sealer.jks
  .docker/secrets/sp/sp-key.pem
  app/application/adapter.js
  app/application/serializer.js
  app/components/app-header/component.js
  app/components/app-header/template.hbs
  app/components/submission-action-cell/component.js
  app/models/file.js
  app/models/submission-action.js
  app/models/submission.js
  config/environment.js
  mirage/config.js
  mirage/factories/file.js
  mirage/factories/submission-action.js
  mirage/factories/submission.js
  mirage/factories/user.js
  mirage/fixtures/files.js
  mirage/fixtures/submission-actions.js
  mirage/fixtures/submissions.js
  mirage/routes/elastic-search.js
  mirage/routes/files.js
  mirage/routes/submission-actions.js
  mirage/routes/submissions.js
  mirage/scenarios/default.js
  mirage/serializers/application.js
  package-lock.json
  package.json
  public/fonts.css
  tests/integration/components/metadata-form-test.js
  yarn.lock
Labels: Deposit UI
